module.exports.tags=[
    "Among Us",
    "Anime Wallpaper",
    "Apex Legends",
    "Ask 9GAG",
    "Coronavirus",
    "Countryballs",
    "Cozy & Comfy",
    "Crappy Design",
    "Cyberpunk 2077",
    "DIY drawing & craft",
    "Football",
    "Fashion & Beauty",
    "Food & Drinks",
    "Fortnite",
    "Game of Thrones",
    "Guy",
    "History",
    "Horror",
    "K-Pop",
    "Latest News",
    "LEGO",
    "Marvel & DC",
    "Movie & TV",
    "Music",
    "NBA",
    "Sport",
    "Wallpaper",
    "Overwatch",
    "PC Master Race",
    "Pokemon",
    "PUBG",
    "Resident Evil 8",
    "Satisfying",
    "Science & Tech",
    "Star Wars",
    "Teens Can Relate",
    "Travel & Photograph",
    "Warhammer",
    "Wholesome",
    "Dark Humor"
]